spring:
  application:
    name: impacto-ext
  data:
    mongodb:
      uri: mongodb+srv://adminUser:${DB_PASSWORD}@impacto-ext.wcrz7wj.mongodb.net/IMPACTO-EXT?appName=IMPACTO-EXT
      uuid-representation: standard
